
code = {
    'OK_LOGIN' : 'Login successfully',
    'OK_LOGOUT' : 'Logout successfully',
    'OK_REGISTRATION' : 'Register successfully',
    'OK_SEND_EMAIL' : 'We just sent you the link to your email',
    'OK_RESET_PASSWORD' : 'Reset password successfully',
    'OK_CHANGE_PASSWORD': 'Change password successfully',
    'OK_SEND_FRIEND_REQUEST': 'Friend request sent successfully',
    'OK_ACCEPT_FRIEND_REQUEST': 'Friend request has been accepted successfully',
    'OK_REJECT_FRIEND_REQUEST': 'Reject friend request successfully',
    'OK_CANCEL_FRIEND_REQUEST': 'Cancel friend request successfully',
    'OK_UNFRIEND': 'Unfriend successfully',
    'OK_SEARCH': 'Return search data successfully',
    'OK_SUGGESTION' : 'Return suggestion data successfully',
    'OK_LIKE': 'Save like successfully',
    'OK_UNLIKE': 'Unlike successfully',
    'OK_SHARE': 'Share successfully',
    'OK_UPDATE': 'Update successfully',
    'OK_GET': 'Get successfully',
    'OK_CREATE': 'Create successfully',
    'OK_UPLOAD': 'Upload successfully',
    'OK_ORDER_SIGNUP': 'Order signup successfully',
    'OK_ORDER_TERMINATE': 'Order terminate successfully',
    'OK_ORDER_RELOCATION': 'Order relocation successfully',
    'OK_DUPLICATE_REQUEST': 'The request is processing',

    'E_NOT_ACTIVE': 'Your account is not active',
    'E_LOGIN_INCORRECT' : 'The email or password that you entered is incorrect',
    'E_IS_LOGIN' :'You are already log in',
    'E_IS_NOT_LOGIN': 'You are not log in',
    'E_SEND_EMAIL_FAIL' : 'There are problems in sending email. Please try again',
    'E_INVALID_PARAMETER_VALUES': 'Request invalid, please verify the parameter',
    'E_USER_NOT_FOUND' : 'User can not be found',
    'E_INVALID_ACTIVATE_KEY': 'Your activation key is invalid',
    'E_DUPLICATE_EMAIL': 'The email has been used already',
    'E_DUPLICATE_USERNAME': 'The username has been used already',
    'E_INVALID_EMAIL': 'The email is not valid',
    'E_INVALID_PASSWORD': 'The password must be at least 8 characters long',
    'E_PASSWORD_MISMATCH': 'Password confirmation mismatch',
    'E_EMAIL_NOT_FOUND': 'Email address not verified for any userprofileManage account',
    'E_SAME_USER': 'Error when userprofileManage sends request to himself',
    'E_ALREADY_SEND_REQUEST': 'Error when userprofileManage has already sent request',
    'E_ALREADY_CONNECT': 'User has already connected with another userprofileManage',
    'E_ALREADY_EXIST': 'This item is already existed',
    'E_NOT_CREATED': 'Cannot create in database',
    'E_REQUEST_NOT_FOUND': 'Cannot find this request',
    'E_POST_NOT_FOUND' : 'Cannot find this post',
    'E_NOT_FOUND':'The requested resource is not found',
    'E_NOT_SAVE': 'Cannot save to database',
    'E_GET_NOT_ALLOW': 'Reject a get request to retrieve userprofileManage profile or something else...',

    'E_DUPLICATE_CUSTOMER': 'The Customer has been used already',

    'E_CUSTOMER_NOT_FOUND': 'Customer can not be found',
    'E_CONSUMER_NOT_FOUND': 'Consumer can not be found',
    'E_PRICEPLAN_NOT_FOUND': 'E_PRICEPLAN_NOT_FOUND',
    'E_REGISTRATION_FAIL': 'There are problems in register. Please try again',
    'E_SALETEAM_NOT_FOUND': 'SaleTeam can not be found',
    'E_TOKEN_FAIL': 'Invalid token.',
    'E_AUTHENTICATION_FAIL': 'Authentication credentials were not provided.',

    'E_REQUEST_VOLTAGE_NOT_FOUND': "Request voltage type out of range",
    'E_REQUEST_METER_NOT_FOUND': "Request meter type out of range",
    'E_REQUEST_PRICEPLAN_NOT_FOUND': 'Request price plan type out of range',

    'E_PAGE_NOT_FOUND': 'Page not found',
    'E_BAD_REQUEST': 'Bad request',
    'E_SERVER_ERROR': 'Server serror',
    'E_PERMISSION_DENY': 'Permission deny',

    'E_PAGINATOR_NOT_FOUND': 'Paginate out of range',
    'E_MAXIMUM_UPLOAD': 'Please keep filesize under 20MB'
}
