# Generated by Django 2.0.3 on 2018-04-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180329_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
